name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Prepare app
        working-directory: ./app
        run: |
          mkdir -p frontend/dist
          touch frontend/dist/.gitkeep

      - name: Run Tests and Generate Coverage
        env:
          APP_ROOT: ${{ GITHUB_ACTION_PATH }}/app
        working-directory: ${{ GITHUB_ACTION_PATH }}/app
        run: |
          go test -v -coverprofile=coverage.out ./...

      - name: Show Coverage
        working-directory: ./app
        run: |
          go tool cover -func=coverage.out
